- src/lib/classes/RegionFactory.class.php
> SEISMICDESIGN-251

- src/lib/classes/DataFactory.class.php
> DataFactory typo

- README.md
The earthquake database will already exist in production, it should be made clear for development purposes that you may need to create this database.
> Update README with create database

- src/lib/classes/usage.ws.php
- src/lib/install/setup_database.php
Per Eric,  this is set up as an include file.  Expecting several globals set,  including five factories.
> Seismicdesign 255

- src/htdocs/index.php
- src/lib/classes/DataFactory.class.php
- src/lib/classes/data.ws.php
- src/lib/install/setup_database.php
> SEISMICDESIGN-256

- src/lib/classes/DataFactory.class.php
- src/lib/classes/FileParser.class.php
- src/lib/classes/SetParser.class.php
- src/lib/install-funcs.inc.php
- src/lib/install/gridded_data.php
- src/lib/install/setup_database.php
- src/lib/install/sql/create_tables.sql
The alaska dataset is configured, but is currently missing pga and pgad files.
This can be tested by updating `src/lib/install/gridded_data.php` to make $pga and $pgad reference other data files that exist, or adding those files to the AK dataset.
> Emcwhirter usgs seismicdesign 247

- example/ActionsView.html
- example/CalculationView.html
- example/example.html
- gruntconfig/browserify.js
- gruntconfig/compass.js
- gruntconfig/connect.js
- package.json
- src/htdocs/css/_ActionsView.scss
- src/htdocs/css/_CalculationView.scss
- src/htdocs/css/index.scss
- src/htdocs/js/ActionsView.js
- src/htdocs/js/Calculation.js
- src/htdocs/js/CalculationView.js
- src/htdocs/js/util/Formatter.js
- test/js/spec/ActionsView.js
- test/js/spec/CalculationTest.js
- test/js/spec/CalculationViewTest.js
- test/js/test.js
Includes commits from #32 and may requires a rebase before merging.
> SEISMICDESIGN-262

- gruntconfig/connect.js
- src/htdocs/service.php
- src/lib/pre-install.php
Test in node,  can't really test apache yet.
> Seismicdesign 257

- gruntconfig/browserify.js
- gruntconfig/connect.js
- src/htdocs/js/WebServiceAccessor.js
- src/htdocs/service.php
- src/lib/pre-install.php
- test/js/spec/WebServiceAccessorTest.js
- test/js/test.js
Includes commits from SEISMICDESIGN-257,  that will have to be committed first.
> Seismicdesign 264

- src/htdocs/js/WebServiceAccessor.js
Just added some comments to the code.
> Added documentation to WebServiceAccessor

- src/htdocs/js/NEHRPCalc2015.js
- test/js/spec/NEHRPCalc2015Test.js
- test/js/test.js
Has a methods which accepts a calculation model with mapped data results and can compute each of the intermediat and final design values necessary for the 2015 NEHRP design code.
> Seismicdesign 265

- .travis.yml
- gruntconfig/copy.js
- package.json
- src/lib/configure.php
- src/lib/install-funcs.inc.php
- src/lib/pre-install.php
- test/js/test.js
- test/js/usage.js
Based on Eric's changes, use static test data.
> Emartinez usgs fix travis

- src/htdocs/js/NEHRPCalc2015.js
- test/js/spec/NEHRPCalc2015Test.js
Updates calculate to include Log and Exp of values.
Cleaned up code, added destroy method and comments.
Updated and added more test.
> Calc up date

- src/htdocs/js/NEHRP2015InputView.js
fixes usgs/earthquake-usdesign#53
- added letter to site class label
> shows value of site class

- package.json
- src/htdocs/js/ActionsView.js
- src/htdocs/js/Application.js
- src/htdocs/js/Calculation.js
- src/htdocs/js/CalculationView.js
- src/htdocs/js/NEHRP2015InputView.js
- src/htdocs/js/WebServiceAccessor.js
Fixes #65
Fixes #67
Fixes #68 
Slightly different approach:
- statuses include "new", "invalid", "ready", "sent", "complete".
- status is updated any time the calculation model changes, until status is "sent" or "complete".
- actions view calculate button triggers "calculate" event.
- application makes request for "ready" calculations up to configurable "concurrentRequests".
> Usgs/earthquake usdesign#65

- src/htdocs/css/_CalculationView.scss
- src/htdocs/js/CalculationView.js
> Usgs/earthquake usdesign#66

- src/htdocs/css/_ActionsView.scss
- src/htdocs/js/ActionsView.js
> Add a print button to ActionsView

- src/htdocs/js/NEHRP2015InputView.js
fixes usgs/earthquake-usdesign#53
- Shows site class prefix in output mode
> Shows site class prefix in Output mode

- gruntconfig/config.js
- src/htdocs/css/_ActionsView.scss
- src/htdocs/css/_CalculationView.scss
- src/htdocs/css/_InputView.scss
- src/htdocs/css/_Nehrp2015ReportView.scss
- src/htdocs/css/_SpectraGraphView.scss
fixes usgs/hazdev-template#184
> Usgs/hazdev template#184

- src/htdocs/_navigation.inc.php
fixes usgs/earthquake-usdesign#125
- Added link to documentation in left nav
> Added documentation link to left navigation

- src/htdocs/js/NEHRP2015InputView.js
fixes usgs/earthquake-usdesign#98
Update the calculation model input values when "please select" is chosen for reference document, site class, and risk category inputs.
> Update inputs when "please select" is chosen

- src/htdocs/js/CalculationView.js
- src/htdocs/js/NEHRP2015InputView.js
fixes usgs/earthquake-usdesign#139
> Update logic when calculations are added and removed

- src/htdocs/js/renderer/nehrp2015/Nehrp2015Section_Summary.js
fixes usgs/earthquake-usdesign#144
> Fix bug in logic that checks s1 and ss thresholds

- src/htdocs/js/renderer/nehrp2015/Nehrp2015Section_11_4_3.js
- src/htdocs/js/renderer/nehrp2015/Nehrp2015Section_11_4_4.js
fixes usgs/earthquake-usdesign#145
> Remove text that has been trumped by more recent changes.

- src/lib/install/sql/reference_data.sql
- test/js/spec/WebServiceAccessorTest.js
- test/js/usage.js
fixes usgs/earthquake-usdesign#148
> changed 2015 NEHRP to 2015 NEHRP Provisions
